"""
أداة تصدير النتائج إلى CSV و PDF
"""
import csv
import os
from datetime import datetime
from utils.logger import log

try:
    from fpdf import FPDF
    HAS_FPDF = True
except ImportError:
    HAS_FPDF = False
    log.warning("fpdf2 غير مثبت - التصدير إلى PDF لن يعمل")


def export_csv(devices, filepath=None):
    if not filepath:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filepath = os.path.expanduser(f"~/NetworkSniperPro_Report_{timestamp}.csv")
    try:
        with open(filepath, 'w', newline='', encoding='utf-8-sig') as f:
            writer = csv.writer(f)
            writer.writerow(["IP Address", "MAC Address", "Hostname", "Vendor", "Status"])
            for dev in devices:
                writer.writerow([dev.get("ip",""), dev.get("mac",""), dev.get("hostname",""), dev.get("vendor",""), dev.get("status","Online")])
        log.info(f"تم تصدير CSV: {filepath}")
        return filepath
    except Exception as e:
        log.error(f"فشل تصدير CSV: {e}")
        return None


def export_pdf(devices, port_results=None, filepath=None):
    if not HAS_FPDF:
        log.error("fpdf2 غير مثبت")
        return None
    if not filepath:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filepath = os.path.expanduser(f"~/NetworkSniperPro_Report_{timestamp}.pdf")
    try:
        pdf = FPDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)
        # Title
        pdf.set_font("Helvetica", "B", 24)
        pdf.cell(0, 15, "Network Sniper Pro", new_x="LMARGIN", new_y="NEXT", align="C")
        pdf.set_font("Helvetica", "", 12)
        pdf.cell(0, 8, f"Scan Report - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", new_x="LMARGIN", new_y="NEXT", align="C")
        pdf.ln(10)
        # Summary
        pdf.set_font("Helvetica", "B", 16)
        pdf.cell(0, 10, f"Devices Found: {len(devices)}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)
        # Device table
        pdf.set_font("Helvetica", "B", 10)
        col_widths = [35, 45, 50, 40, 20]
        headers = ["IP Address", "MAC Address", "Hostname", "Vendor", "Status"]
        pdf.set_fill_color(30, 30, 50)
        pdf.set_text_color(255, 255, 255)
        for i, header in enumerate(headers):
            pdf.cell(col_widths[i], 8, header, border=1, fill=True, align="C")
        pdf.ln()
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(0, 0, 0)
        for dev in devices:
            pdf.cell(col_widths[0], 7, dev.get("ip",""), border=1, align="C")
            pdf.cell(col_widths[1], 7, dev.get("mac","")[:17], border=1, align="C")
            pdf.cell(col_widths[2], 7, dev.get("hostname","")[:20], border=1, align="C")
            pdf.cell(col_widths[3], 7, dev.get("vendor","")[:18], border=1, align="C")
            pdf.cell(col_widths[4], 7, dev.get("status","Up"), border=1, align="C")
            pdf.ln()
        # Port results
        if port_results:
            pdf.ln(10)
            pdf.set_font("Helvetica", "B", 16)
            pdf.cell(0, 10, "Port Scan Results", new_x="LMARGIN", new_y="NEXT")
            pdf.ln(3)
            for ip, ports in port_results.items():
                pdf.set_font("Helvetica", "B", 12)
                pdf.cell(0, 8, f"Host: {ip}", new_x="LMARGIN", new_y="NEXT")
                pdf.set_font("Helvetica", "", 9)
                pdf.set_fill_color(30, 30, 50)
                pdf.set_text_color(255, 255, 255)
                for h, w in zip(["Port","Service","State","Risk"], [25,40,30,60]):
                    pdf.cell(w, 7, h, border=1, fill=True, align="C")
                pdf.ln()
                pdf.set_text_color(0, 0, 0)
                for pi in ports:
                    pdf.cell(25, 7, str(pi.get("port","")), border=1, align="C")
                    pdf.cell(40, 7, pi.get("service",""), border=1, align="C")
                    pdf.cell(30, 7, pi.get("state",""), border=1, align="C")
                    pdf.cell(60, 7, pi.get("risk",""), border=1, align="C")
                    pdf.ln()
                pdf.ln(5)
        # Footer
        pdf.ln(10)
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(128, 128, 128)
        pdf.cell(0, 8, "Generated by Network Sniper Pro v2.0", new_x="LMARGIN", new_y="NEXT", align="C")
        pdf.output(filepath)
        log.info(f"تم تصدير PDF: {filepath}")
        return filepath
    except Exception as e:
        log.error(f"فشل تصدير PDF: {e}")
        return None
